#ifndef _GieseMultipole_H_
#define _GieseMultipole_H_

extern const double GlobalAlmC[];

namespace ccdl
{
void SolidHarm_Rlm_S( double const * crd, double const r2, double * Rlm );
void SolidHarm_Rlm_P( double const * crd, double const r2, double * Rlm );
void SolidHarm_Rlm_D( double const * crd, double const r2, double * Rlm );
void SolidHarm_Rlm_F( double const * crd, double const r2, double * Rlm );
void SolidHarm_Rlm_G( double const * crd, double const r2, double * Rlm );
void SolidHarm_Rlm_H( double const * crd, double const r2, double * Rlm );
void SolidHarm_Rlm_I( double const * crd, double const r2, double * Rlm );
void SolidHarm_Rlm_J( double const * crd, double const r2, double * Rlm );
void SolidHarm_Rlm_K( double const * crd, double const r2, double * Rlm );
void SolidHarm_Rlm_L( double const * crd, double const r2, double * Rlm );
void SolidHarm_Rlm_M( double const * crd, double const r2, double * Rlm );


void ClmTranslation_SS( double const * crd, double const r2, double * W );
void ClmTranslation_PS( double const * crd, double const r2, double * W );
void ClmTranslation_PP( double const * crd, double const r2, double * W );
void ClmTranslation_DS( double const * crd, double const r2, double * W );
void ClmTranslation_DP( double const * crd, double const r2, double * W );
void ClmTranslation_DD( double const * crd, double const r2, double * W );
void ClmTranslation_FS( double const * crd, double const r2, double * W );
void ClmTranslation_FP( double const * crd, double const r2, double * W );
void ClmTranslation_FD( double const * crd, double const r2, double * W );
void ClmTranslation_FF( double const * crd, double const r2, double * W );
void ClmTranslation_GS( double const * crd, double const r2, double * W );
void ClmTranslation_GP( double const * crd, double const r2, double * W );
void ClmTranslation_GD( double const * crd, double const r2, double * W );
void ClmTranslation_GF( double const * crd, double const r2, double * W );
void ClmTranslation_GG( double const * crd, double const r2, double * W );
void ClmTranslation_HS( double const * crd, double const r2, double * W );
void ClmTranslation_HP( double const * crd, double const r2, double * W );
void ClmTranslation_HD( double const * crd, double const r2, double * W );
void ClmTranslation_HF( double const * crd, double const r2, double * W );
void ClmTranslation_HG( double const * crd, double const r2, double * W );
void ClmTranslation_HH( double const * crd, double const r2, double * W );


void PrimGauExpInt_Overlap_SS( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Overlap_PS( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Overlap_PP( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Overlap_DS( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Overlap_DP( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Overlap_DD( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Overlap_FS( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Overlap_FP( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Overlap_FD( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Overlap_FF( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Overlap_GS( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Overlap_GP( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Overlap_GD( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Overlap_GF( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Overlap_GG( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Overlap_HS( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Overlap_HP( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Overlap_HD( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Overlap_HF( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Overlap_HG( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Overlap_HH( double const zab, double const * crd, double const r2, double * X );

void PrimGauExpInt_Ewald_SS( double const sqrt_za, double const * crd, double const r2, double * X );
void PrimGauExpInt_Ewald_PS( double const sqrt_za, double const * crd, double const r2, double * X );
void PrimGauExpInt_Ewald_PP( double const sqrt_za, double const * crd, double const r2, double * X );
void PrimGauExpInt_Ewald_DS( double const sqrt_za, double const * crd, double const r2, double * X );
void PrimGauExpInt_Ewald_DP( double const sqrt_za, double const * crd, double const r2, double * X );
void PrimGauExpInt_Ewald_DD( double const sqrt_za, double const * crd, double const r2, double * X );
void PrimGauExpInt_Ewald_FS( double const sqrt_za, double const * crd, double const r2, double * X );
void PrimGauExpInt_Ewald_FP( double const sqrt_za, double const * crd, double const r2, double * X );
void PrimGauExpInt_Ewald_FD( double const sqrt_za, double const * crd, double const r2, double * X );
void PrimGauExpInt_Ewald_FF( double const sqrt_za, double const * crd, double const r2, double * X );
void PrimGauExpInt_Ewald_GS( double const sqrt_za, double const * crd, double const r2, double * X );
void PrimGauExpInt_Ewald_GP( double const sqrt_za, double const * crd, double const r2, double * X );
void PrimGauExpInt_Ewald_GD( double const sqrt_za, double const * crd, double const r2, double * X );
void PrimGauExpInt_Ewald_GF( double const sqrt_za, double const * crd, double const r2, double * X );
void PrimGauExpInt_Ewald_GG( double const sqrt_za, double const * crd, double const r2, double * X );
void PrimGauExpInt_Ewald_HS( double const sqrt_za, double const * crd, double const r2, double * X );
void PrimGauExpInt_Ewald_HP( double const sqrt_za, double const * crd, double const r2, double * X );
void PrimGauExpInt_Ewald_HD( double const sqrt_za, double const * crd, double const r2, double * X );
void PrimGauExpInt_Ewald_HF( double const sqrt_za, double const * crd, double const r2, double * X );
void PrimGauExpInt_Ewald_HG( double const sqrt_za, double const * crd, double const r2, double * X );
void PrimGauExpInt_Ewald_HH( double const sqrt_za, double const * crd, double const r2, double * X );

void PrimGauExpInt_Coulomb_SS( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Coulomb_PS( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Coulomb_PP( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Coulomb_DS( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Coulomb_DP( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Coulomb_DD( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Coulomb_FS( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Coulomb_FP( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Coulomb_FD( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Coulomb_FF( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Coulomb_GS( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Coulomb_GP( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Coulomb_GD( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Coulomb_GF( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Coulomb_GG( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Coulomb_HS( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Coulomb_HP( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Coulomb_HD( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Coulomb_HF( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Coulomb_HG( double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Coulomb_HH( double const zab, double const * crd, double const r2, double * X );
void ExpInt_UserAux_SS( double const * O, double const * crd, double const r2, double * X );
void ExpInt_UserAux_PS( double const * O, double const * crd, double const r2, double * X );
void ExpInt_UserAux_PP( double const * O, double const * crd, double const r2, double * X );
void ExpInt_UserAux_DS( double const * O, double const * crd, double const r2, double * X );
void ExpInt_UserAux_DP( double const * O, double const * crd, double const r2, double * X );
void ExpInt_UserAux_DD( double const * O, double const * crd, double const r2, double * X );
void ExpInt_UserAux_FS( double const * O, double const * crd, double const r2, double * X );
void ExpInt_UserAux_FP( double const * O, double const * crd, double const r2, double * X );
void ExpInt_UserAux_FD( double const * O, double const * crd, double const r2, double * X );
void ExpInt_UserAux_FF( double const * O, double const * crd, double const r2, double * X );
void ExpInt_UserAux_GS( double const * O, double const * crd, double const r2, double * X );
void ExpInt_UserAux_GP( double const * O, double const * crd, double const r2, double * X );
void ExpInt_UserAux_GD( double const * O, double const * crd, double const r2, double * X );
void ExpInt_UserAux_GF( double const * O, double const * crd, double const r2, double * X );
void ExpInt_UserAux_GG( double const * O, double const * crd, double const r2, double * X );
void ExpInt_UserAux_HS( double const * O, double const * crd, double const r2, double * X );
void ExpInt_UserAux_HP( double const * O, double const * crd, double const r2, double * X );
void ExpInt_UserAux_HD( double const * O, double const * crd, double const r2, double * X );
void ExpInt_UserAux_HF( double const * O, double const * crd, double const r2, double * X );
void ExpInt_UserAux_HG( double const * O, double const * crd, double const r2, double * X );
void ExpInt_UserAux_HH( double const * O, double const * crd, double const r2, double * X );

void PrimGauExpPot_Overlap_SS( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Overlap_PS( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Overlap_PP( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Overlap_DS( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Overlap_DP( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Overlap_DD( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Overlap_FS( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Overlap_FP( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Overlap_FD( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Overlap_FF( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Overlap_GS( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Overlap_GP( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Overlap_GD( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Overlap_GF( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Overlap_GG( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Overlap_HS( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Overlap_HP( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Overlap_HD( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Overlap_HF( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Overlap_HG( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Overlap_HH( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );

void PrimGauExpPot_Ewald_SS( double const sqrt_za,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Ewald_PS( double const sqrt_za,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Ewald_PP( double const sqrt_za,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Ewald_DS( double const sqrt_za,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Ewald_DP( double const sqrt_za,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Ewald_DD( double const sqrt_za,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Ewald_FS( double const sqrt_za,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Ewald_FP( double const sqrt_za,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Ewald_FD( double const sqrt_za,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Ewald_FF( double const sqrt_za,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Ewald_GS( double const sqrt_za,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Ewald_GP( double const sqrt_za,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Ewald_GD( double const sqrt_za,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Ewald_GF( double const sqrt_za,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Ewald_GG( double const sqrt_za,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Ewald_HS( double const sqrt_za,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Ewald_HP( double const sqrt_za,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Ewald_HD( double const sqrt_za,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Ewald_HF( double const sqrt_za,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Ewald_HG( double const sqrt_za,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Ewald_HH( double const sqrt_za,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );

void PrimGauExpPot_Coulomb_SS( double const zab,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Coulomb_PS( double const zab,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Coulomb_PP( double const zab,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Coulomb_DS( double const zab,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Coulomb_DP( double const zab,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Coulomb_DD( double const zab,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Coulomb_FS( double const zab,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Coulomb_FP( double const zab,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Coulomb_FD( double const zab,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Coulomb_FF( double const zab,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Coulomb_GS( double const zab,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Coulomb_GP( double const zab,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Coulomb_GD( double const zab,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Coulomb_GF( double const zab,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Coulomb_GG( double const zab,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Coulomb_HS( double const zab,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Coulomb_HP( double const zab,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Coulomb_HD( double const zab,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Coulomb_HF( double const zab,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Coulomb_HG( double const zab,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void PrimGauExpPot_Coulomb_HH( double const zab,  double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void ExpPot_UserAux_SS( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void ExpPot_UserAux_PS( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void ExpPot_UserAux_PP( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void ExpPot_UserAux_DS( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void ExpPot_UserAux_DP( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void ExpPot_UserAux_DD( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void ExpPot_UserAux_FS( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void ExpPot_UserAux_FP( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void ExpPot_UserAux_FD( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void ExpPot_UserAux_FF( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void ExpPot_UserAux_GS( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void ExpPot_UserAux_GP( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void ExpPot_UserAux_GD( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void ExpPot_UserAux_GF( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void ExpPot_UserAux_GG( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void ExpPot_UserAux_HS( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void ExpPot_UserAux_HP( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void ExpPot_UserAux_HD( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void ExpPot_UserAux_HF( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void ExpPot_UserAux_HG( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );
void ExpPot_UserAux_HH( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb );

void PrimGauExpGrd_Overlap_SS( double const zab, double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Overlap_PS( double const zab, double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Overlap_PP( double const zab, double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Overlap_DS( double const zab, double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Overlap_DP( double const zab, double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Overlap_DD( double const zab, double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Overlap_FS( double const zab, double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Overlap_FP( double const zab, double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Overlap_FD( double const zab, double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Overlap_FF( double const zab, double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Overlap_GS( double const zab, double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Overlap_GP( double const zab, double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Overlap_GD( double const zab, double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Overlap_GF( double const zab, double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Overlap_GG( double const zab, double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Overlap_HS( double const zab, double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Overlap_HP( double const zab, double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Overlap_HD( double const zab, double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Overlap_HF( double const zab, double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Overlap_HG( double const zab, double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Overlap_HH( double const zab, double const * crd, double const r2, double * X, double * G );

void PrimGauExpGrd_Ewald_SS( double const sqrt_za,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Ewald_PS( double const sqrt_za,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Ewald_PP( double const sqrt_za,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Ewald_DS( double const sqrt_za,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Ewald_DP( double const sqrt_za,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Ewald_DD( double const sqrt_za,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Ewald_FS( double const sqrt_za,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Ewald_FP( double const sqrt_za,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Ewald_FD( double const sqrt_za,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Ewald_FF( double const sqrt_za,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Ewald_GS( double const sqrt_za,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Ewald_GP( double const sqrt_za,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Ewald_GD( double const sqrt_za,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Ewald_GF( double const sqrt_za,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Ewald_GG( double const sqrt_za,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Ewald_HS( double const sqrt_za,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Ewald_HP( double const sqrt_za,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Ewald_HD( double const sqrt_za,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Ewald_HF( double const sqrt_za,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Ewald_HG( double const sqrt_za,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Ewald_HH( double const sqrt_za,  double const * crd, double const r2, double * X, double * G );

void PrimGauExpGrd_Coulomb_SS( double const zab,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Coulomb_PS( double const zab,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Coulomb_PP( double const zab,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Coulomb_DS( double const zab,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Coulomb_DP( double const zab,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Coulomb_DD( double const zab,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Coulomb_FS( double const zab,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Coulomb_FP( double const zab,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Coulomb_FD( double const zab,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Coulomb_FF( double const zab,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Coulomb_GS( double const zab,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Coulomb_GP( double const zab,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Coulomb_GD( double const zab,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Coulomb_GF( double const zab,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Coulomb_GG( double const zab,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Coulomb_HS( double const zab,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Coulomb_HP( double const zab,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Coulomb_HD( double const zab,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Coulomb_HF( double const zab,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Coulomb_HG( double const zab,  double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Coulomb_HH( double const zab,  double const * crd, double const r2, double * X, double * G );
void ExpGrd_UserAux_SS( double const * O, double const * crd, double const r2, double * X, double * G );
void ExpGrd_UserAux_PS( double const * O, double const * crd, double const r2, double * X, double * G );
void ExpGrd_UserAux_PP( double const * O, double const * crd, double const r2, double * X, double * G );
void ExpGrd_UserAux_DS( double const * O, double const * crd, double const r2, double * X, double * G );
void ExpGrd_UserAux_DP( double const * O, double const * crd, double const r2, double * X, double * G );
void ExpGrd_UserAux_DD( double const * O, double const * crd, double const r2, double * X, double * G );
void ExpGrd_UserAux_FS( double const * O, double const * crd, double const r2, double * X, double * G );
void ExpGrd_UserAux_FP( double const * O, double const * crd, double const r2, double * X, double * G );
void ExpGrd_UserAux_FD( double const * O, double const * crd, double const r2, double * X, double * G );
void ExpGrd_UserAux_FF( double const * O, double const * crd, double const r2, double * X, double * G );
void ExpGrd_UserAux_GS( double const * O, double const * crd, double const r2, double * X, double * G );
void ExpGrd_UserAux_GP( double const * O, double const * crd, double const r2, double * X, double * G );
void ExpGrd_UserAux_GD( double const * O, double const * crd, double const r2, double * X, double * G );
void ExpGrd_UserAux_GF( double const * O, double const * crd, double const r2, double * X, double * G );
void ExpGrd_UserAux_GG( double const * O, double const * crd, double const r2, double * X, double * G );
void ExpGrd_UserAux_HS( double const * O, double const * crd, double const r2, double * X, double * G );
void ExpGrd_UserAux_HP( double const * O, double const * crd, double const r2, double * X, double * G );
void ExpGrd_UserAux_HD( double const * O, double const * crd, double const r2, double * X, double * G );
void ExpGrd_UserAux_HF( double const * O, double const * crd, double const r2, double * X, double * G );
void ExpGrd_UserAux_HG( double const * O, double const * crd, double const r2, double * X, double * G );
void ExpGrd_UserAux_HH( double const * O, double const * crd, double const r2, double * X, double * G );

void PrimGauExpPotGrd_Overlap_SS( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Overlap_PS( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Overlap_PP( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Overlap_DS( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Overlap_DP( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Overlap_DD( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Overlap_FS( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Overlap_FP( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Overlap_FD( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Overlap_FF( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Overlap_GS( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Overlap_GP( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Overlap_GD( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Overlap_GF( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Overlap_GG( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Overlap_HS( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Overlap_HP( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Overlap_HD( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Overlap_HF( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Overlap_HG( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Overlap_HH( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );

void PrimGauExpPotGrd_Ewald_SS( double const sqrt_za, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Ewald_PS( double const sqrt_za, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Ewald_PP( double const sqrt_za, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Ewald_DS( double const sqrt_za, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Ewald_DP( double const sqrt_za, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Ewald_DD( double const sqrt_za, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Ewald_FS( double const sqrt_za, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Ewald_FP( double const sqrt_za, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Ewald_FD( double const sqrt_za, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Ewald_FF( double const sqrt_za, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Ewald_GS( double const sqrt_za, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Ewald_GP( double const sqrt_za, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Ewald_GD( double const sqrt_za, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Ewald_GF( double const sqrt_za, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Ewald_GG( double const sqrt_za, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Ewald_HS( double const sqrt_za, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Ewald_HP( double const sqrt_za, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Ewald_HD( double const sqrt_za, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Ewald_HF( double const sqrt_za, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Ewald_HG( double const sqrt_za, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Ewald_HH( double const sqrt_za, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );

void PrimGauExpPotGrd_Coulomb_SS( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Coulomb_PS( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Coulomb_PP( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Coulomb_DS( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Coulomb_DP( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Coulomb_DD( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Coulomb_FS( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Coulomb_FP( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Coulomb_FD( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Coulomb_FF( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Coulomb_GS( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Coulomb_GP( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Coulomb_GD( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Coulomb_GF( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Coulomb_GG( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Coulomb_HS( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Coulomb_HP( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Coulomb_HD( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Coulomb_HF( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Coulomb_HG( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void PrimGauExpPotGrd_Coulomb_HH( double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );

void ExpPotGrd_UserAux_SS( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void ExpPotGrd_UserAux_PS( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void ExpPotGrd_UserAux_PP( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void ExpPotGrd_UserAux_DS( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void ExpPotGrd_UserAux_DP( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void ExpPotGrd_UserAux_DD( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void ExpPotGrd_UserAux_FS( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void ExpPotGrd_UserAux_FP( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void ExpPotGrd_UserAux_FD( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void ExpPotGrd_UserAux_FF( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void ExpPotGrd_UserAux_GS( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void ExpPotGrd_UserAux_GP( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void ExpPotGrd_UserAux_GD( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void ExpPotGrd_UserAux_GF( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void ExpPotGrd_UserAux_GG( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void ExpPotGrd_UserAux_HS( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void ExpPotGrd_UserAux_HP( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void ExpPotGrd_UserAux_HD( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void ExpPotGrd_UserAux_HF( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void ExpPotGrd_UserAux_HG( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );
void ExpPotGrd_UserAux_HH( double const * O, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * G );


void SolidHarm_Rlm_Switch( int const lmax, double const * crd, double const r2, double * X );
void ClmTranslation_Switch( int const la, int const lb, double const * crd, double const r2, double * X );


void PrimGauExpInt_Overlap_Switch( int const la, int const lb, double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Ewald_Switch( int const la, int const lb, double const zab, double const * crd, double const r2, double * X );
void PrimGauExpInt_Coulomb_Switch( int const la, int const lb, double const zab, double const * crd, double const r2, double * X );


void PrimGauExpGrd_Overlap_Switch( int const la, int const lb, double const zab, double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Ewald_Switch( int const la, int const lb, double const zab, double const * crd, double const r2, double * X, double * G );
void PrimGauExpGrd_Coulomb_Switch( int const la, int const lb, double const zab, double const * crd, double const r2, double * X, double * G );


void PrimGauExpPot_Overlap_Switch( int const la, int const lb, double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb  );
void PrimGauExpPot_Ewald_Switch( int const la, int const lb, double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb  );
void PrimGauExpPot_Coulomb_Switch( int const la, int const lb, double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb  );


void PrimGauExpPotGrd_Overlap_Switch( int const la, int const lb, double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * grd  );
void PrimGauExpPotGrd_Ewald_Switch( int const la, int const lb, double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * grd  );
void PrimGauExpPotGrd_Coulomb_Switch( int const la, int const lb, double const zab, double const * crd, double const r2, double const * qa, double const * qb, double * pa, double * pb, double * grd  );

}


#include "GieseMultipoleInline.hpp"

#endif

